services:
  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - auth_db_data:/var/lib/postgresql/data
      - ./auth-simulator/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - app-network

  frontend:
    image: node:18-alpine
    working_dir: /app
    ports:
      - 3000:3000
    volumes:
      - ./auth-simulator:/app
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_NAME=postgres
      - DB_PORT=5432
    command: >
      sh -c "npm install &&
             npm run dev"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  auth_db_data:
    name: auth_db_data